SERVER:
  NAME: Spider_TYC_Enterprise
  VERSION: 1.0.0
  DEBUG: True
  KEYS: 环保设备,化工设备,涂料设备,管道安装,保温管道,通风设备
  RUN_MODE: process  # single单进程 process多进程 gevent多协程
  IS_TEST_BREAK: False


PAGINATION:
  MIN_PAGE: 20
  MAX_PAGE: 21
  PAGINATION: 10  # 默认config.py中设置为10


LOG:
  LOG_DIR:
  LOG_LEVEL: debug
  LOG_FORMATTER: '%(asctime)s - %(pathname)s[line:%(lineno)d] - %(levelname)s - %(message)s'
  LOG_FILENAME_PREFIX: spider_tyc_enterprise


DB:
  DB_LINK: mysql+pymysql://enter:e2a7106f1cc8bb1e1318df70aa0a3540@212.64.61.62:3306/enterprise?charset=utf8


FILES:
  OUTPUT_BASE_DIR: excel


STORE:
  EXCEL: False
  DB: True


APIS:
  API_MODE: pro   # pc-pro专业版 pc-tyc普通版(正常注册用户)
  TYC_SEARCH: https://www.tianyancha.com/search
  TYC_DETAIL: https://www.tianyancha.com/company
  TYC_PRO_SEARCH: https://pro.tianyancha.com/search
  TYC_PRO_DETAIL: https://pro.tianyancha.com
  TYC_COOKIE:
  IS_PLUS_CITY: False
  IS_PLUS_CITY_SUB: True
  PLUS_CITYS: 125,127,157


PROXY:
  IS_RUN: True
  API: http://212.64.61.62:5555/random
